name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    
    
    services:
      database:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: simpson
          MYSQL_DATABASE: django_pos
        ports:  ['3306:3306']
        #options: --tmpfs /var/lib/mysql
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
   

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
  
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Tests
      env: 
        DBENGINE: django.db.backends.mysql
        DATABASE_NAME: django_pos
        DATABASE_USERNAME: simpson
        DATABASE_PASSWORD: 
        DATABASE_BHOST: 127.0.0.1
        DATABASE_PORT: 3306
       
      run: |
        sudo /etc/init.d/mysql start
        python manage.py migrate    
        python manage.py test
     
