name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    
    
    services:
      database:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: 
        ports:
        - 3306:3306
        options: --tmpfs /var/lib/mysql
    
    env:
      DB_HOST: 127.0.0.1
      DB_DATABASE: django_pos
      DB_USER: root
      DB_PASSWORD: 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
  
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py test

