name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    
    
    services:
      database:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: simpson
          MYSQL_DATABASE: django_pos
        ports:  ['3306:3306']
        #options: --tmpfs /var/lib/mysql
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
   

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
  
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        sudo /etc/init.d/mysql start
        sudo mysql CREATE USER 'simpson'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'
        sudo mysql GRANT ALL PRIVILEGES ON *.* TO 'simpson'@'localhost' WITH GRANT OPTION;
        python manage.py migrate

      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: django_pos
        DBUSER: simpson
        DBPASSWORD: password
        DBHOST: 127.0.0.1
        DBPORT: $
       

    - name: Run Tests
      run: |
        sudo /etc/init.d/mysql start
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: django_pos
        DBUSER: simpsom
        DBPASSWORD: password
        DBHOST: 127.0.0.1
        DBPORT: $
