name: Django application

on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        MYSQL_ALLOW_EMPTY_PASSWORD: no


    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          #MYSQL_ALLOW_EMPTY_PASSWORD: yes
    
  
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env: 
         DBENGINE: django.db.backends.mysql
         DATABASE_NAME: django_pos
         DATABASE_USERNAME: simpson
         DATABASE_PASSWORD: simpsom
         DATABASE_BHOST: 127.0.0.1
         DATABASE_PORT: 3306
       
        run: |
         sudo /etc/init.d/mysql start
         python manage.py test
     